<?xml version="1.0"?>

<st-source>
<time-stamp>From VisualWorks® NonCommercial, 7.6 of March 3, 2008 on November 25, 2008 at 12:47:21 pm</time-stamp>


<name-space>
<name>OregonTrail</name>
<environment>Smalltalk</environment>
<private>false</private>
<imports>
			private Smalltalk.*
			</imports>
<category></category>
<attributes>
<package>OregonTrail</package>
</attributes>
</name-space>

<shared-variable>
<name>DBManager</name>
<environment>OregonTrail</environment>
<private>false</private>
<constant>false</constant>
<category>New Share</category>
<initializer>DatabaseManager new</initializer>
<attributes>
<package>OregonTrail</package>
</attributes>
</shared-variable>

<initialize>
<variable-id>OregonTrail.DBManager</variable-id>
</initialize>

</st-source>
